baseurl: "https://jsanchez.uy/"
title: Jorge Sánchez
theme: ghostwriter
languageCode: en-us
copyright: Jorge Sánchez
# TODO: googleAnalytics: XXX
disqusShortname: blog-jsanchez-uy
pygmentsUseClasses: true
pygmentsCodefences: true

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name:
  profile: ""

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: Jorge Sánchez
  description:
  github: "https://github.com/jsanchezuy"
#  gitlab: "https://gitlab.com/XXX"
#  linkedin: "https://linkedin.com/in/XXX/"
  twitter: "https://twitter.com/jsanchezuy"
#  stackoverflow: "https://stackoverflow.com/users/XXX/YYY"
#  facebook: "https://www.facebook.com/username"
  email: jsanchezsilvera@gmail.com
  opengraph: true
  shareTwitter: true
  rss: true
  shareFacebook: true
  shareLinkedIn: true
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

permalinks:
  post: "/:day/:month/:year/:filename/"


menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Projects
      url: /projects/
      weight: 2

# Menus Original
# menu:
#   main:
#     - name: Blog
#       url: /
#       weight: 1
#     - name: Projects
#       url: /project/
#       weight: 2
#     - name: Contact
#       url: /page/contact/
#       weight: 3
#     - name: About
#       url: /page/about/
#       weight: 4
